### ISSUE TITLE
Missing blocks in outline

### ISSUE THREAD

**Issue by Wuerfel21** [ironsheep/P2-vscode-langserv-extension#2]
### and have you...

- [X] I updated to the latest spin2 version available
- [X] I have restarted VSCode and the problem still exists

### Version of Spin2 Language Server VScode Extension with the issue

it auto-updates to the latest when you restart vsc you gormless issue template

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Hardware, Operating System, Operating System version, VSCode version

Hardware: Commodore 128DCR
OS Ver: CP/M 3.0
VSCode Ver: VSCodium 1.85.1

### Description of problem

In https://github.com/IRQsome/NeoYume/blob/master/neoyume_lower.spin2

A number of DAT blocks and associated labels no longer show up in the outline, notably the LSPC and memory arbiter sections.

**Comment by ironsheep** [comment]
Am working on this and more... increasing support for conditional compile a bit. May be up to a week before update is released.

**Comment by ironsheep** [comment]
Ada, I think I've fixed this, but I need your review.  Does v2.2.15 address this completely?

**Comment by Wuerfel21** [comment]
Appears to be fixed :+1:

**Comment by ironsheep** [comment]
Good to hear. Thank you.
