### ISSUE TITLE
Strange parse issues in SPCcog file

### ISSUE THREAD

**Issue by Wuerfel21** [ironsheep/P2-vscode-langserv-extension#3]
### and have you...

- [X] I updated to the latest spin2 version available
- [X] I have restarted VSCode and the problem still exists

### Version of Spin2 Language Server VScode Extension with the issue

the one... you know the one... with like the colors and the text and the... you know?

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Hardware, Operating System, Operating System version, VSCode version

Hardware: Sinneslöschen Cross-Development System Mk.3
OS Ver: Concurrent DOS 386 2.0
VSCode Ver: VSCodium 1.85.1

### Description of problem

it be brok
![image](https://github.com/ironsheep/P2-vscode-langserv-extension/assets/6944842/3063175e-516d-4218-9adc-96e711c640dc)
![image](https://github.com/ironsheep/P2-vscode-langserv-extension/assets/6944842/b498416c-2efc-4c1c-ba3f-6fab7eeda9fe)

**Comment by Wuerfel21** [comment]
[spcog_v1_2_1.zip](https://github.com/ironsheep/P2-vscode-langserv-extension/files/14789778/spcog_v1_2_1.zip)

**Comment by ironsheep** [comment]
Thank you, as always, for reporting this! But AUGH! I'm deep in some work on this extension that is taking longer than I expected, so I can't get a fix to you quickly. I'll push for another week on my current extension work, and if I don't wrap it, I'll then try to drop an interim fix to you.

**Comment by ironsheep** [comment]
Ok, fixes committed and will appear in v2.2.15, and later.
