### ISSUE TITLE
Missing WORDFIT/BYTEFIT keywords

### ISSUE THREAD

**Issue by Wuerfel21** [ironsheep/P2-vscode-langserv-extension#6]
### and have you...

- [X] I updated to the latest spin2 version available
- [X] I have restarted VSCode and the problem still exists

### Version of Spin2 Language Server VScode Extension with the issue

yes

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Hardware, Operating System, Operating System version, VSCode version

I am a teapot

### Description of problem

![image](https://github.com/ironsheep/P2-vscode-langserv-extension/assets/6944842/94e018b5-7111-4aee-8a75-f77bcca65845)

WORDFIT/BYTEFIT directive is not supported. Also I just noticed while taking the screenshot that the collapse arrow is there twice for some reason.

### Additional information

A file (current MisoYume draft version): 
[misoyume_lower.spin2.zip](https://github.com/ironsheep/P2-vscode-langserv-extension/files/14967656/misoyume_lower.spin2.zip)

**Comment by ironsheep** [comment]
fixed wordfit bytefit. changes will appear in v2.2.16 and later.

Still working on fold issue.

**Comment by ironsheep** [comment]
Ok, folding changes in v2.2.16 and later.

Please see if this fixed the folding issue. Let me know
