### ISSUE TITLE
ALIGNL in VAR section is not correctly handled

### ISSUE THREAD

**Issue by Wuerfel21** [ironsheep/P2-vscode-langserv-extension#9]
### and have you...

- [X] I updated to the latest spin2 version available
- [X] I have restarted VSCode and the problem still exists

### Version of Spin2 Language Server VScode Extension with the issue

oomfie my head

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Hardware, Operating System, Operating System version, VSCode version

The unusual

### Description of problem

![image](https://github.com/ironsheep/P2-vscode-langserv-extension/assets/6944842/81572535-2124-4abe-b53b-0437768a564a)

The second ALIGNL is flagged as `P2 Spin Duplicate name [alignl], global variable/constant already exists`, so it seems the keyword isn't recognized at all

**Comment by ironsheep** [comment]
on it!

**Comment by ironsheep** [comment]
Changes committed. Fix will appear in v2.2.17 and later
